// <auto-generated />
using System;
using DriverTime.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DriverTime.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260614102830_AddDriverFieldsToDddFile")]
    partial class AddDriverFieldsToDddFile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DriverTime.Domain.Entities.CountryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DddFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EntryTimeUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DddFileId");

                    b.ToTable("CountryEntries");
                });

            modelBuilder.Entity("DriverTime.Domain.Entities.DddFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DriverCardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverFirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverLastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("DddFiles");
                });

            modelBuilder.Entity("DriverTime.Domain.Entities.DriverActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DddFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DddFileId");

                    b.ToTable("DriverActivities");
                });

            modelBuilder.Entity("DriverTime.Domain.Entities.VehicleUse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DddFileId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DddFileId");

                    b.ToTable("VehicleUses");
                });

            modelBuilder.Entity("DriverTime.Domain.Entities.CountryEntry", b =>
                {
                    b.HasOne("DriverTime.Domain.Entities.DddFile", "DddFile")
                        .WithMany("CountryEntries")
                        .HasForeignKey("DddFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DddFile");
                });

            modelBuilder.Entity("DriverTime.Domain.Entities.DriverActivity", b =>
                {
                    b.HasOne("DriverTime.Domain.Entities.DddFile", "DddFile")
                        .WithMany("DriverActivities")
                        .HasForeignKey("DddFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DddFile");
                });

            modelBuilder.Entity("DriverTime.Domain.Entities.VehicleUse", b =>
                {
                    b.HasOne("DriverTime.Domain.Entities.DddFile", "DddFile")
                        .WithMany("VehicleUses")
                        .HasForeignKey("DddFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DddFile");
                });

            modelBuilder.Entity("DriverTime.Domain.Entities.DddFile", b =>
                {
                    b.Navigation("CountryEntries");

                    b.Navigation("DriverActivities");

                    b.Navigation("VehicleUses");
                });
#pragma warning restore 612, 618
        }
    }
}
